services:
  db:
    image: postgres:bullseye
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
